[tool.pydocstyle]
ignore = "D100,D101,D102,D103,D104,D105,D106,D107,D203,D210,D212,D401,D403"


[tool.ruff]
preview = true
line-length = 120

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint]
select = ["F", "I", "SLF", "SIM"]
